export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#222222 \
  --color=bg:#282828 \
  --color=border:#ffffff \
  --color=fg:#dddddd \
  --color=fg+:#ffffff \
  --color=gutter:#282828 \
  --color=header:#ffffff \
  --color=hl+:#d9ba73 \
  --color=hl:#d9ba73 \
  --color=info:#606060 \
  --color=marker:#ff7676 \
  --color=pointer:#ffffff \
  --color=prompt:#ffffff \
  --color=query:#dddddd:regular \
  --color=scrollbar:#dddddd \
  --color=separator:#ffffff \
  --color=spinner:#606060 \
"
